context: .
        push:true
        tags:
          ${{ env.DOCKER_USERNAME }}/telegram-referral-bot:latest
          ${{ env.DOCKER_USERNAME }}/telegram-referral-bot:${{ github.sha }}
        platforms: |
          linux/amd64
          linux/arm64
